/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/components/modals/AboutModal.vue')['default']
    ChannelContextMenu: typeof import('./src/components/items/ChannelContextMenu.vue')['default']
    ChannelList: typeof import('./src/components/lists/ChannelList.vue')['default']
    ChannelModel: typeof import('./src/components/items/ChannelModel.vue')['default']
    ChatBox: typeof import('./src/components/messages/ChatBox.vue')['default']
    GroupMemberModel: typeof import('./src/components/items/GroupMemberModel.vue')['default']
    MemberContextMenu: typeof import('./src/components/items/MemberContextMenu.vue')['default']
    MemberMessageBubble: typeof import('./src/components/messages/MemberMessageBubble.vue')['default']
    MenuButton: typeof import('./src/components/items/MenuButton.vue')['default']
    MessageBubbleComponents: typeof import('./src/components/messages/MessageBubbleComponents.vue')['default']
    MessageContextMenu: typeof import('./src/components/messages/MessageContextMenu.vue')['default']
    ParticipantsList: typeof import('./src/components/lists/ParticipantsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/inputs/SearchBar.vue')['default']
    ServerContextMenu: typeof import('./src/components/items/ServerContextMenu.vue')['default']
    ServerList: typeof import('./src/components/lists/ServerList.vue')['default']
    ServerNameModel: typeof import('./src/components/modals/ServerNameModel.vue')['default']
    SettingButton: typeof import('./src/components/items/SettingModel/SettingButton.vue')['default']
    SettingInput: typeof import('./src/components/items/SettingModel/SettingInput.vue')['default']
    SettingSwitch: typeof import('./src/components/items/SettingModel/SettingSwitch.vue')['default']
    SettingTreeSelect: typeof import('./src/components/items/SettingModel/SettingTreeSelect.vue')['default']
    TextArea: typeof import('./src/components/inputs/TextArea.vue')['default']
    UserComponent: typeof import('./src/components/users/UserComponent.vue')['default']
    UserMessageBubble: typeof import('./src/components/messages/UserMessageBubble.vue')['default']
  }
}
