/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/features/servers/presentation/components/modals/AboutModal.vue')['default']
    ChannelContextMenu: typeof import('./src/features/channels/presentation/components/items/ChannelContextMenu.vue')['default']
    ChannelList: typeof import('./src/features/channels/presentation/components/lists/ChannelList.vue')['default']
    ChannelModel: typeof import('./src/features/channels/presentation/components/items/ChannelModel.vue')['default']
    ChannelRail: typeof import('./src/features/chat/presentation/components/layout/ChannelRail.vue')['default']
    ChannelSettingsMenu: typeof import('./src/features/chat/presentation/components/menus/ChannelSettingsMenu.vue')['default']
    ChatBox: typeof import('./src/features/chat/presentation/components/messages/ChatBox.vue')['default']
    ChatCenter: typeof import('./src/features/chat/presentation/components/layout/ChatCenter.vue')['default']
    ComposerHost: typeof import('./src/features/chat/presentation/components/composer/ComposerHost.vue')['default']
    CoreTextBubble: typeof import('./src/features/chat/presentation/components/messages/CoreTextBubble.vue')['default']
    CoreTextMessageBubble: typeof import('./src/features/chat/message-flow/message/presentation/components/CoreTextMessageBubble.vue')['default']
    CreateChannelDialog: typeof import('./src/features/chat/presentation/components/dialogs/CreateChannelDialog.vue')['default']
    DeleteChannelDialog: typeof import('./src/features/chat/presentation/components/dialogs/DeleteChannelDialog.vue')['default']
    DomainSelector: typeof import('./src/features/chat/presentation/components/composer/DomainSelector.vue')['default']
    FileMessageBubble: typeof import('./src/features/files/presentation/components/FileMessageBubble.vue')['default']
    FileRefMessageBubble: typeof import('./src/features/chat/message-flow/message/presentation/components/FileRefMessageBubble.vue')['default']
    FileUploadButton: typeof import('./src/features/chat/message-flow/upload/presentation/components/FileUploadButton.vue')['default']
    GovernancePageShell: typeof import('./src/features/chat/room-governance/presentation/components/GovernancePageShell.vue')['default']
    GroupMemberModel: typeof import('./src/features/channels/presentation/components/items/GroupMemberModel.vue')['default']
    MemberContextMenu: typeof import('./src/features/chat/presentation/components/MemberContextMenu.vue')['default']
    MemberMessageBubble: typeof import('./src/features/chat/presentation/components/messages/MemberMessageBubble.vue')['default']
    MembersRail: typeof import('./src/features/chat/presentation/components/layout/MembersRail.vue')['default']
    MenuButton: typeof import('./src/features/servers/presentation/components/items/MenuButton.vue')['default']
    MessageBubbleComponents: typeof import('./src/features/chat/presentation/components/messages/MessageBubbleComponents.vue')['default']
    MessageContentHost: typeof import('./src/features/chat/message-flow/message/presentation/components/MessageContentHost.vue')['default']
    MessageContextMenu: typeof import('./src/features/chat/presentation/components/menus/MessageContextMenu.vue')['default']
    ModuleCard: typeof import('./src/features/plugins/presentation/components/ModuleCard.vue')['default']
    ModuleDetailDrawer: typeof import('./src/features/plugins/presentation/components/ModuleDetailDrawer.vue')['default']
    ModuleProgress: typeof import('./src/features/plugins/presentation/components/ModuleProgress.vue')['default']
    ParticipantsList: typeof import('./src/features/channels/presentation/components/lists/ParticipantsList.vue')['default']
    PluginCenterCatalogGrid: typeof import('./src/features/plugins/presentation/components/PluginCenterCatalogGrid.vue')['default']
    PluginCenterFilterRail: typeof import('./src/features/plugins/presentation/components/PluginCenterFilterRail.vue')['default']
    PluginCenterGridHeader: typeof import('./src/features/plugins/presentation/components/PluginCenterGridHeader.vue')['default']
    QuickSwitcher: typeof import('./src/features/chat/presentation/components/overlay/QuickSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/features/chat/presentation/components/inputs/SearchBar.vue')['default']
    ServerContextMenu: typeof import('./src/features/servers/presentation/components/items/ServerContextMenu.vue')['default']
    ServerInfoCard: typeof import('./src/features/servers/presentation/components/cards/ServerInfoCard.vue')['default']
    ServerInfoModal: typeof import('./src/features/servers/presentation/components/modals/ServerInfoModal.vue')['default']
    ServerList: typeof import('./src/features/servers/presentation/components/lists/ServerList.vue')['default']
    ServerManagerModal: typeof import('./src/features/servers/presentation/components/modals/ServerManagerModal.vue')['default']
    ServerNameModel: typeof import('./src/features/servers/presentation/components/modals/ServerNameModel.vue')['default']
    ServerRail: typeof import('./src/features/chat/presentation/components/layout/ServerRail.vue')['default']
    SettingButton: typeof import('./src/features/settings/presentation/components/SettingModel/SettingButton.vue')['default']
    SettingInput: typeof import('./src/features/settings/presentation/components/SettingModel/SettingInput.vue')['default']
    SettingSwitch: typeof import('./src/features/settings/presentation/components/SettingModel/SettingSwitch.vue')['default']
    SettingTreeSelect: typeof import('./src/features/settings/presentation/components/SettingModel/SettingTreeSelect.vue')['default']
    SignalStrip: typeof import('./src/features/chat/message-flow/message/presentation/components/SignalStrip.vue')['default']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TextArea: typeof import('./src/features/chat/presentation/components/inputs/TextArea.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TOption: typeof import('tdesign-vue-next')['Option']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    UnknownDomainCard: typeof import('./src/features/chat/message-flow/message/presentation/components/UnknownDomainCard.vue')['default']
    UploadProgress: typeof import('./src/features/chat/message-flow/upload/presentation/components/UploadProgress.vue')['default']
    UserComponent: typeof import('./src/features/user/presentation/components/UserComponent.vue')['default']
    UserMessageBubble: typeof import('./src/features/chat/presentation/components/messages/UserMessageBubble.vue')['default']
  }
}
